A = input().split(" ")
B = input().split(" ")
C = input().split(" ")
a = int(A[0])
b = int(A[1])
c = int(B[0])
d = int(B[1])
e = int(B[2])
f = int(C[0])
g = int(C[1])
h = int(C[2])

print(a,b)
print(c,d,e)
print(f,g,h)